코드리뷰용
dasi-bom/dasi-bom-server pull request #45
Opened 2023-07-07 14:56 UTC by minju412

### 🧐 Motivation
- 코드를 추가/변경하게 된 이유를 작성해 주세요

<br>

### 🎯 Key Changes
- 주요 구현 사항을 작성해 주세요

<br>

### 💬 To Reviewers
- 리뷰어에게 전달할 말을 작성해 주세요

2023-07-08 05:48 UTC, h-beeen commented on src/main/java/com/example/server/config/auth/PrincipalDetails.java
> +	public Member getUser() {
1. getUser의 리턴값이 Member 객체로 구성되어 있네요. `Member member`형태로 통일해서 사용하고 ,
2.`@Getter` 어노테이션으로 깔끔하게 정리하는 것도 좋을 것 같다는 생각이 들어요

2023-07-08 05:51 UTC, h-beeen commented on src/main/java/com/example/server/config/jwt/dto/RefreshToken.java
> +    public RefreshToken(final String refreshToken, final String memberId) {
여기서도 `@AllArgsConstructor`를 사용하면 코드 수를 줄일 수 있을 것 같은데, 생성자를 따로 적어주신 이유가 있을까요?

2023-07-08 05:53 UTC, h-beeen commented on src/main/java/com/example/server/config/jwt/exception/TokenValidFailedException.java
> +        super("Failed to generate Token.");
실제 개발 단계에 들어가기 전에, 응답을 내릴 때 던지는 Exception Form에 대해 같이 고민해보는 것도 좋을 것 같아요.
에러코드 및 같이 던져줄 내용에 어떤 내용이 포함될 지 정해보면 좋을 것 같아요.
다음 PR에서 제가 간단하게 정리해서 올려볼게요.

2023-07-08 05:57 UTC, h-beeen commented on src/main/java/com/example/server/config/oauth/PrincipalOauth2UserService.java
> +	private MemberRepository userRepository;
Member - User는 동일 관계라고 판단이 되는데, Member와 User를 구분해서 작성하신 이유도 궁금합니다.

2023-07-08 05:59 UTC, h-beeen commented on src/main/java/com/example/server/config/oauth/provider/KakaoUserInfo.java
> +    public String getEmail() {
```
public String getEmail() {
    return Optional.ofNullable(attributes.get("kakao_account"))
            .map(account -> (String) ((Map<String, Object>) account).get("email"))
            .orElse(null);
}
```java

스트림 문법으로 바꾸면 조금 더 직관적이고 깔끔한 코드가 나올 것 같아요!

2023-07-08 06:03 UTC, h-beeen commented on src/main/java/com/example/server/config/oauth/provider/KakaoUserInfo.java
> +    @Override
다른 함수들도 stream 문법으로 변경해 보시는 걸 추천드리고 싶어요!

2023-07-08 06:05 UTC, h-beeen commented on src/main/java/com/example/server/config/oauth/provider/OAuth2Provider.java
> +public enum OAuth2Provider {
`@Getter`, `@RequiredArgsConstructor` 어노테이션을 사용한다면 조금 더 깔끔한 코드 구성이 가능할 것 같아요.

2023-07-08 06:09 UTC, h-beeen commented on src/main/java/com/example/server/controller/MemberController.java
> +            throw new CustomException(FILE_NOT_EXIST_ERROR);
위에서 언급 드렸던, ExceptionForm 정의 파일이네요.
ErrorCode 에 개발자가 식별 가능한 변수 (예를 들면 EX001, EX002), Exception 발생 시간 등 다양한 내용들이 들어가는 추세라고 알고 있어요!
앞으로, 개발 하면서 표준 에러 응답에 대한 폼도 같이 고민해봅시다!

2023-07-08 06:19 UTC, h-beeen commented on src/main/java/com/example/server/domain/Member.java
> +	public void updateProfileInfo(String nickname) {
1. 닉네임 관련 검증 로직인 것으로 이해가 됩니다.
- updateProfileInfo보다는 nickname에 관련된 명명이 더 직관적이지 않을까 싶습니다.
- isNotBlank를 해당 업데이트 로직에서 검증해야할까?? 라는 의문이 듭니다.
- updateProfileInfo 함수를 호출하는 부분에서 이미 Blank까지 검증이 된 상태로, 도메인 로직에서는 정상적인 인자에 한해 업데이트 하는 로직만을 포함하는게 SRP를 조금 더 잘 준수한 코드라고 생각이 듭니다!

2023-07-08 06:20 UTC, h-beeen commented on src/main/java/com/example/server/dto/ApiResponse.java
> +public class ApiResponse<T> {
ResponseEntity에 대한 폼인 것 같아요! 깔끔하고 직관적으로 작성된 것 같습니다!

2023-07-08 06:25 UTC, h-beeen commented on src/main/java/com/example/server/repository/MemberRepository.java
> +public interface MemberRepository extends JpaRepository<Member, Long> {
조회와 
레포지토리를 Query, Commande등으로 분리하는 측면이 추후 디버깅 / 테스트코드 / 성능적인 측면에서 훨씬 우수하므로, 이 부분을 고려해 보시는 것도 좋을 것 같습니다.
(단, repo 는 find, register, modify 이렇게 상세하게 나누실 필요는 없습니다!)

2023-07-08 06:29 UTC, h-beeen commented on src/main/java/com/example/server/service/MemberServiceImpl.java
> +        if (memberRepository.existsByNickname(reqDto.getNickname())) {
중복 닉네임을 검증하는 Service 계층의 void 함수로 만들어서 한 줄로 정리하면 (메소드 분리) 더 깔끔할 것 같습니다.

2023-07-08 06:41 UTC, h-beeen requested changes
민주님과 협업을 진행하면서, 첫 코드리뷰를 진행했습니다.

[좋았던 점]
- Service 계층에서 인터페이스와 인터페이스 구현 클래스로 분리한 점이 좋았습니다.
- 각 함수의 접근제한자가 적절하게 사용되었습니다.

[아쉬웠던 점]
- 조회(findBy, existsBy)와 등록(save, update)이 하나의 Repository 계층에서 실행됩니다.
- argsConstrucor, Getter가 통일되어 사용되지 않은 점이 아쉬웠습니다.
- Update... 로직의 경우, 함수 분리를 통해, 각 함수의 책임을 분할하면 좋을 것 같습니다.
- if문 여러번 중첩되는 로직에서 stream 문법을 통해 직관적으로 변경하면 더 좋을 것 같습니다.

[ 확인해주세요! ]
- CustomException을 바탕으로 리턴할 때, 내릴 표준 예외 폼과, 성공할 때 내려줄 응답에 대한 표준 응답 폼에 대해서 같이 고민해보면 좋을 것 같습니다.

2023-07-13 02:36 UTC, minju412 commented on src/main/java/com/example/server/config/jwt/dto/RefreshToken.java
> +    public RefreshToken(final String refreshToken, final String memberId) {
이유는 따로 없었고 놓친 부분이었네요..! 수정했습니다!

2023-07-13 02:46 UTC, minju412 commented on src/main/java/com/example/server/config/oauth/PrincipalOauth2UserService.java
> +	private MemberRepository userRepository;
Member와 User를 따로 구분하려는 의도는 아니었어서 `memberRepository`로 수정했습니다!
도메인 이름을 `User` 대신 `Member`로 설정한 것은, Spring Security 내부에 `User` 클래스가 이미 정의되어 있기 때문에 실수를 예방하고자 `Member`로 설정했습니다.

2023-07-13 02:56 UTC, minju412 commented on src/main/java/com/example/server/config/oauth/provider/KakaoUserInfo.java
> +    public String getEmail() {
훨씬 깔끔한 것 같아요! 스트림 문법에 익숙해져야겠네요! 😄

2023-07-13 04:02 UTC, minju412 commented on src/main/java/com/example/server/controller/MemberController.java
> +            throw new CustomException(FILE_NOT_EXIST_ERROR);
ErrorCode에 다양한 내용을 담아 활용할 수 있겠군요! 
선민님께 현재 `ErrorResponse`에 http 상태코드를 포함해달라는 요청을 받았었는데, 상태코드를 포함해서 같이 고민해보면 좋을 것 같아요!

2023-07-13 04:04 UTC, minju412 commented on src/main/java/com/example/server/config/jwt/exception/TokenValidFailedException.java
> +        super("Failed to generate Token.");
넵넵!! 함께 고민해봐요! 😊

2023-07-13 05:28 UTC, minju412 commented on src/main/java/com/example/server/domain/Member.java
> +	public void updateProfileInfo(String nickname) {
- `updateProfileInfo()`는 사용자 정보를 갱신하기 위해서 만든 함수인데요, 현재 사용자 정보는 `소셜 로그인을 통해 끌어온 정보` + `직접 입력 정보`로 이루어져 있습니다! 아직까지 `직접 입력 정보`는 닉네임 밖에 없지만 나중에 다른 필드가 추가되었을 때를 생각해 `updateProfileInfo()`라는 이름을 사용했습니다.
- `isNotBlank`는 말씀해주신대로 이미 검증된 데이터가 넘어오는게 좋을 것 같네요! 코드 수정했습니다. 감사합니다!

2023-07-13 06:20 UTC, minju412 commented on src/main/java/com/example/server/repository/MemberRepository.java
> +public interface MemberRepository extends JpaRepository<Member, Long> {
말씀해 주신 내용을 처음 접해봤는데, 유용한 패턴인 것 같아요! (CQS 키워드로 구글링을 해보았는데 의도하신게 맞겠죠..?😅)
하지만 아직 익숙지 않아 레포지토리에 해당 패턴을 어떻게 적용할지 감이 잘 오지 않네요.. 이 부분은 도움을 받을 수 있을까요..?!

2023-07-13 06:39 UTC, minju412 commented
꼼꼼한 리뷰 정말 감사합니다 🙇‍♀️
앞으로는, 혼자 개발할 때 크게 신경쓰지 못했던 OOP 설계 원칙에 대해서 함께 고민할 수 있을 것 같아 기대가 됩니다!
표준 예외 폼은 저도 고민해보겠습니다, 같이 이야기 나눠봐요!

2023-07-13 06:44 UTC, minju412 commented on src/main/java/com/example/server/repository/MemberRepository.java
> +public interface MemberRepository extends JpaRepository<Member, Long> {
말씀해주신 내용에 대해 CQS 라는 키워드로 구글링 해봤는데, 처음 접해보는 내용이라 흥미로웠습니다!
다만 해당 패턴을 repository에 어떻게 적용해야할 지 감이 잘 오지 않네요..ㅜㅜ
아직 익숙지 않아 이 부분 도움을 받을 수 있을까요..??
```
public interface MemberQueryRepository extends JpaRepository<Member, Long> {
findBy, existsBy, ...
}
```
```
public interface MemberCommandRepository extends JpaRepository<Member, Long> {
save, update, ...
}
```
이런 식으로 하는게 맞을까요?! 🤔

2023-07-21 08:28 UTC, closed without merging