Feature/52 - Add tests for existing codebase
dasi-bom/dasi-bom-server pull request #56
Opened 2023-07-26 14:01 UTC by minju412

### 🧐 Motivation
- 기존 코드에 대한 테스트 코드를 작성했습니다.

<br>

### 🎯 Key Changes
- `프로필 정보 등록`에 대한 성공/실패 테스트 작성
- `프로필 이미지 업로드`에 대한 성공/실패 테스트 작성

<br>

### 💬 To Reviewers
- 이전 회의 때 컨트롤러 테스트는 우선 작성하지 않기로 한 것 같아서 서비스 테스트만 작성했습니다.
    - 제가 놓친 테스트가 있다면 말씀해 주세요!
- 기존에 존재하던 `service/S3Service`와 `service/S3ServiceImpl`는 삭제하고 같은 동작을 하는 `util/S3Uploader`를 생성했습니다. 
    - 그 이유는 S3에 업로드하는 행위은 비즈니스 로직보다는 기능을 수행하는 라이브러리 성격이 강하다고 생각했기 때문입니다!

2023-07-30 06:17 UTC, h-beeen commented on src/main/java/com/example/server/domain/Image.java
> +	@Builder
@Builder 어노테이션과 함께 생성자를 정의하신 이유가 궁금합니다!

2023-07-30 06:21 UTC, h-beeen commented on src/main/java/com/example/server/util/S3Uploader.java
> +		img.setImgUrl(url);
img 객체의 `@Setter` 메소드가 꼭 필요한 존재라고 생각하시는지 궁금합니다! 저는 updateXXX라는 편의 메소드를 구현해서, fileName과 ImgUrl을 업데이트 하는 메소드로 구현했을 것 같아요!

2023-07-30 06:29 UTC, h-beeen commented on src/test/java/com/example/server/service/MemberServiceTest.java
> +			.isInstanceOf(CustomException.class);
`isInstanceOf`로 `CustomException` -> `BusinessException`으로 바뀌는 부분에서 아마 Exception이 날 것 같아요.

또한, isInstanceOf로 CustomException 내의 오류가 맞다고 할 지라도, 개발자가 의도한 오류(ex. E001, G001) 등의 정확한 에러를 검증하는 로직이 없어도 의도대로 assert문에서 동작할 수 있을지 궁금합니다.

2023-07-30 06:33 UTC, h-beeen requested changes
수고 많으셨습니다!
궁금한 사항은 코멘트로 달아두었고,
`@Setter`의 사용은 개인적으로 수정이 필요할 것 같아 코멘트 남겼습니다!!

깔끔하고 간결하게 테스트코드까지 짜시느라 고생 많으셨습니다 :)
아마 컨플릭 잡는게 쉽지 않을 것으로 예상이 됩니다...ㅠ

2023-07-30 13:47 UTC, minju412 commented on src/main/java/com/example/server/domain/Image.java
> +	@Builder
사용되지 않는 어노테이션이었네요..! 제거했습니다! :)

2023-07-30 13:51 UTC, minju412 commented on src/main/java/com/example/server/util/S3Uploader.java
> +		img.setImgUrl(url);
고민 없이 setter를 사용했던 흔적이 남아있었네요 😅 제안해 주신 대로 변경했습니다!

2023-07-30 13:56 UTC, minju412 commented on src/test/java/com/example/server/service/MemberServiceTest.java
> +			.isInstanceOf(CustomException.class);
해빈님께서 작성하신 코드와 머지된 상태가 아니라서 제 로컬에서는 잘 작동합니다..! 
머지 후 해당 테스트 코드는 수정하도록 하겠습니다!

2023-07-30 16:20 UTC, h-beeen approved these changes

2023-07-31 11:47 UTC, minju412 commented
인텔리제이에서 conflict 해결 후 머지했습니다!

2023-07-31 11:58 UTC, closed without merging