Feature/64 - Modify Pet Service / Pet Controller / Pet Domain
dasi-bom/dasi-bom-server pull request #67
Opened 2023-08-04 02:20 UTC by h-beeen

### 🧐 Motivation
- 코드를 추가/변경하게 된 이유를 작성해 주세요

<br>

### 🎯 Key Changes

## 전역 수정사항
- `import static method` 를 활용해 `ErrorCode` 와 같은 직관적 이해가 가능한 요소들에 대한 축약
- `Member`, `Pet` 을 `BaseEntity`를 활용하여 `Auditing` 하여 생성 시간, 수정 시간 컬럼 구조 수정
- `MySQL` 로컬 시간 오류 변경 `[UTC]` -> `[UTC + 9] Seoul/Asia`

##Member Controller
- `~/pet/profile` URL을 통한`Post` Request로 사용자가 펫 프로필 정보 신규 등록이 가능합니다.

```JavaScript
POST /pet/profile
Host : localhost:8080
Authorization : Bearer ${ACCESS_TOKEN}
Content-type : application/json
```

- `~/pet/profile/images/` URL을 통한 `Post` Request로 펫 프로필 이미지 등록이 가능합니다.
- `~/pet/profile/` URL을 통한 `Patch` Request로 사용자가 펫 프로필 정보 수정이 가능합니다.
- 

<br>

### 💬 To Reviewers
- 리뷰어에게 전달할 말을 작성해 주세요

2023-08-04 13:26 UTC, minju412 requested changes
예외 처리까지 꼼꼼하게 진행하시느라 고생 많으셨습니다! 세세한 리드미 아주 좋네요👍
코멘트에서도 말씀드렸듯이 `Service`, `FindService`, `UpdateService`로 나누는 것이 좋을까? 에 대해서 함께 고민해보면 좋을 것 같아요! 
머지 후에 개발하신 부분 ERD와 API Docs 까지 작성 부탁드릴게요 :)

2023-08-04 13:26 UTC, minju412 commented on src/main/java/com/example/server/domain/pet/model/Pet.java
> +		validateType(petReq.getType());
위에서 제안드린 `validate()` 메소드를 이 곳에서도 재활용할 수 있다면 좋을 것 같네요!

2023-08-04 13:26 UTC, minju412 commented on src/main/java/com/example/server/domain/pet/model/Pet.java
>  		final String type,
둥물 타입을 String으로 설정하신 것은 직접입력 필드 때문인 것 같아요. 하지만 Enum이 아닐 경우 개, 강아지 등 다양한 형태로 들어오는 데이터를 정형화할 수 없을 것 같다는 의견입니다..! 
`Pet` 엔티티에 직접입력을 선택했을 때 입력할 수 있는 컬럼을 추가하는건 어떨까요?
강아지, 고양이 등 Enum으로 들어온다면 해당 필드는 null로 채워두고, 직접 입력을 선택했을 때에만 사용하는 식으로요!

2023-08-04 13:26 UTC, minju412 commented on src/main/java/com/example/server/domain/pet/api/dto/PetProfileRequest.java
>  	private Integer age;
소수 혹은 문자열처럼 다른 타입을 입력했을 때 예외처리가 되어있는지 궁금합니다!

2023-08-04 13:41 UTC, minju412 commented on src/main/java/com/example/server/domain/pet/model/Pet.java
> +	private LocalDate endTempProtectedDate;
`보호 종료일`과 함께 현재 `보호중`인지 `보호종료`인지를 알리는 상태필드가 필요할 것 같습니다! 기본값은 `보호중`으로 신규 동물 프로필 등록 시 따로 입력값을 받지는 않고, 동물 프로필 수정에서 `보호종료`를 선택할 수 있도록 하는건 어떨지 의견 드립니다!

2023-08-04 13:57 UTC, h-beeen commented on src/main/java/com/example/server/domain/pet/api/PetProfileController.java
> +		@RequestBody PetProfileRequest reqDto,
RequestDto 분리는 변경에 있어서 조금 더 유연한 설계가 될 것 같아요. 해당 부분 수정해서 반영하겠습니다. 감사합니다!

2023-08-04 13:58 UTC, h-beeen commented on src/main/java/com/example/server/domain/pet/api/dto/PetProfileRequest.java
> +	private String bio;
biography(전기)의 약자로 보통 short bio라고 하면 짧은 자기소개 정도로 해석한다고 알고 있어요.
bio는 실 생활에서도 자주 쓰이는 약어로 직관적으로 괜찮은 변수명이라 판단해서 명명했습니다.

2023-08-04 14:01 UTC, h-beeen commented on src/main/java/com/example/server/domain/pet/api/dto/PetProfileRequest.java
> +	@DateTimeFormat(pattern = "yyyy-MM-dd")
사실 `yyyy-MM-dd`가 아니더라도, 모든 `LocalDate`를 담을 수 있습니다. 다만 LocalDateTime의 형태로 요청이 들어온다면, 예기치 않은 Exception이 발생하게 됩니다.(Type Conflict)

이 부분을 제약적인 공간에 기술하다 보니 의미 해석이 조금 난해했던 것 같아요.
해당 부분은 위에 적은 대로 모든 LocalDate 변수 처리가 가능합니다!
임보 시작일이라는 변수를 사용자에게 시간까지 포함해서 요청받지 않을거라고 예상이 되는데,
정규표현식 제약조건까지 필요할 지 질문 드려보고 싶습니다!

2023-08-04 14:05 UTC, h-beeen commented on src/main/java/com/example/server/domain/pet/model/Pet.java
> +	@Column(length = 511)
앞서, 이 부분은 도메인 제약 조건 변경으로 수정하는게 좋을 것 같아요.
VARCHAR(300)으로 수정하는게 훨씬 직관적일 것 같아요.

일단 length가 300 이상이어야 했고, 기존 (256-1)로 255바이트였던 것을 (512-1) 로 계산했다는 풍문을 조심스럽게 전달드립니다ㅎ

2023-08-04 14:10 UTC, h-beeen commented on src/main/java/com/example/server/domain/pet/model/Pet.java
>  		final String type,
해당 부분 수정의 필요성에 대해서 공감합니다!
다만, 엔티티를 수정하는 것 보다, 기획 파트에서 이 부분을 `그룹화`해서 처리하는 것에 대해서 선행해서 얘기해 보는 것은 어떨까요?
강아지 타입이 간혹 홍보메세지나, 다른 용도로 악용될 수 있을 것 같다는 생각도 들더라구요.

엔티티 자체를 확실하게 ENUM으로 그룹화하고, 기존 `String type`을 `Enum type`으로 관리하는 건 어떨까 생각이 들어요.
임시보호의 특성 상, 동물의 종류가 아무리 많아야 10종류 정도일 것 같다는 생각이 듭니다.

2023-08-04 14:16 UTC, h-beeen commented on src/main/java/com/example/server/domain/pet/api/dto/PetProfileRequest.java
>  	private Integer age;
문자열의 경우에는 아래 사진처럼 JsonParser Global Exception으로 핸들링합니다.

<img width="555" alt="스크린샷 2023-08-04 오후 11 13 22" src="https://github.com/dasi-bom/dasi-bom-server/assets/112257466/6df11115-4fa1-4905-9784-0f682a758754">

다만 Integer 객체의 경우 자연스럽게 타입캐스팅이 된다는 사실을 망각했네요.

Long(Out of Range-Json Parser Error), 
String(InvalidFormat-Json Parser Error)
등으로 자연스럽게 처리되지만

소수의 경우에는, 소수점을 버림한 Integer로 자연스럽게 타입캐스팅이 되서 반영이 되네요.
지금 막 테스트케이스를 짜고 있던 참인데, 파라미터에 Not Integer Long Number는 넣어 볼 생각은 했는데,
소수는 생각 못했던 것 같아요!

너무나도 좋은 예외를 찾아주신 것 같아요!
꼼꼼하게 리뷰해주셔서 감사드립니다.

2023-08-04 14:20 UTC, h-beeen commented on src/main/java/com/example/server/domain/pet/model/Pet.java
> +	private LocalDate endTempProtectedDate;
Default Status `Enum tempProtectedStatus` 필드에 대해서 지난번에도 코드리뷰 주셨었던 점 기억합니다.

_tempProtectedStatus Enum 엔티티에 대한 고민중에 있습니다.
임시보호 상태를 어떻게 전역으로 신뢰성 있게 관리할지에 대해서 고민 후 작성 예정입니다._

이번 코드에 반영하지 않았던 이유는 위 내용이 설명드릴 수 있을 것 같아요.

Default를 보호중으로 해두고, 보호 종료를 Update할 수 있도록 설정하는 것도 좋은 옵션이 될 것 같아요.

다만, 보호 종료로 바뀌었을 때 해당 Pet에 대해 임시보호를 했던 사용자가 어떤 권한이 달라지는지 확인 부탁드립니다.
- 임시보호가 종료된다면, PetList에 표시해야 하는가? (ownerId로 임시보호중인 Pet을 찾는 쿼리에서의 제약조건 변동)
- 임시보호 종료 유저에게는 어떤 API가 제공될 예정인지?

중도 합류라서 아직 이런 비즈니스 흐름을 따라가기 조금 버겁네요 ㅠ
이런 부분에 대한 세세한 수정이 잦더라도, 지금처럼 섬세한 코드리뷰 부탁드립니다 :)

2023-08-04 14:29 UTC, h-beeen commented on src/main/java/com/example/server/domain/member/application/MemberFindService.java
> +	public Member findBySecurityUsername(String username) {
맞습니다. 기본적으로 JPA 메소드인 `findByID`는 

```java
Optional<T> findById(ID id);
```

Returns whether an entity with the given id exists.
Params: id – must not be null.
Returns: true if an entity with the given id exists, false otherwise.
Throws: IllegalArgumentException – if id is null.

위와 같은 형식을 가집니다.

조회 메소드를 findService로 분리한 이유는 말씀하신대로 예외처리를 우리가 정의한 
`BusinessException` 으로 전역에서 처리하기 위해서입니다.

Repository계층에서 해당 메소드를 호출하면, 불필요한 코드 중복이 예상되기 때문입니다.

2023-08-04 14:33 UTC, h-beeen commented on src/main/java/com/example/server/domain/member/application/MemberFindService.java
> +	public Member findBySecurityUsername(String username) {
`findByProviderId()`의 경우 Jpa 메소드로 MemberQueryRepository에 기 정의된 함수여서 중복 네이밍을 피하고자 해당 메소드를 작명하게 되었습니다.

Jpa메소드와 중복인 상황에서 어떤 메소드 명명이 더 현명하다고 판단하시는지 궁금합니다.

2023-08-04 14:43 UTC, h-beeen commented on src/main/java/com/example/server/domain/pet/application/PetUpdateService.java
> +public class PetUpdateService {
정말 좋은 설계란 무엇인가? 에 대한 끊임없이 하게 만들어주신 좋은 질문인 것 같아요.

UpdateService의 `savePetProfile()`의 필요성과, Service와 Update의 분리 필요성에 대해서 다시 한번 곰곰히 생각해봤어요.

- 비즈니스 로직의 성격이 다른가?
    - create의 성격(success httpStatus 201) / update의 성격(success httpStatus 200)의 느낌으로 분리해보려고 했어요.
    - 성격은 다른 것 같다고 판단됩니다. 펫의 신규 생성과, 업데이트 간 수정 가능한 컬럼에 대해서는 차이가 있다고 생각했어요.

- `savePetProfile(Pet pet)` 메소드는 필요한 함수인가?
    - 결론은 `필요 없다고 판단`된다 입니다.
    - `save` 메소드의 경우 기본적으로 원본 객체의 given Type을 반환합니다. findBy처럼 `Optional <T>`형식이 아니에요!
    - 그러면 예외처리를 할 필요가 없는데, 서비스 레이어에서 직접 참조하면 되지 않을까?

해당 사항에 대해 조금 더 고민 후 답변 달아드릴 수 있을 것 같아요.
우아한 테크코스에서 굉장히 괜찮은 레퍼런스를 찾아왔어요. [BE | Service에서 Service를 의존할까 Repository(Dao)를 의존할까 | 2022.05.24 #15](https://github.com/woowacourse/retrospective/discussions/15)

한 번 같이 읽어보시고, 토요일 날 같이 이야기 나눠봐요!

2023-08-04 14:52 UTC, h-beeen commented on src/main/java/com/example/server/domain/pet/model/Pet.java
>  		validateOwner(owner);
안 그래도, 펫 엔티티에 대해 너무 많은 컬럼이 들어있는 사안에 대해 문제점을 인식하고 이번 토요일에 말씀 드려보고 싶었습니다.

```bash
A long parameter list can indicate that a new structure should be created to wrap the numerous parameters or that the function is doing too many things.
```

SonarLint에서 생성자는 최대 7개의 파라미터를 받는 것을 권장합니다.
Pet Entity의 구조 자체가 점점 더 복잡해지고 있는 느낌이 강하게 듭니다.

반려동물에 대한 도메인 요구조건이 더 늘어날 것으로 예상이 되는데, 이 부분에 대해서 엔티티 분리도 고려를 해야하나 싶어요.

말씀주셨던, 개인적으로 validate 메소드를 각자 위치시키는 것이 조금 더 SOLID 원칙에서 OCP를 준수한 것이 아닐까..? 라는 생각이 들어요.
지금은 생성자의 멤버변수 파라미터가 과도하게 많아져서 validate 명령어가 중복적으로 나열되는 느낌이라고 생각이 듭니다!

단순히 모든 메소드를 합쳐서 void형으로 묶어주는 설계 VS 줄수를 많이 차지하는 1줄씩 쓰는 설계
어떤 점이 효율적인지는 개발자의 선택이겠지만, 저는 여기서는 validate를 분리하는것이 조금더 OCP에 근접한 설계라고 생각합니다!

2023-08-04 14:56 UTC, h-beeen commented on src/main/java/com/example/server/domain/pet/model/Pet.java
> +		validateType(petReq.getType());
```java
		validateType(petReq.getType());
		validateName(petReq.getName());
		validateStartTempProtectedDate(petReq.getStartTempProtectedDate());
		validateAge(petReq.getAge());
		validateBio(petReq.getBio());
```

```java
		validateOwner(owner);
		validateType(type);
		validateName(name);
		validateStartTempProtectedDate(startTempProtectedDate);
		validateAge(age);
		validateBio(bio);
```

최초 신규 등록과, 업데이트가 요구하는 생성자의 파라미터가 달라서 해당 부분에 대한 반영을 동일 메소드로 재활용하기는 어려워보여요.
한다면 교집합 (Type, Name, Start--, Age, Bio) 이렇게 5개의 영역만 감싸서 묶어야 하는데
그렇다면 예상 결과는

```java
		validateAll(petReq.getType() ... );
```

```java
		validateOwner(owner);
                 validateAll(petReq.getType() ...);
```

이런 느낌으로 나올 것 같아요.

조금은 취향에 가까운 부분이겠지만, Update 이외에도 Dto가 요구하는 파라미터를 직관적으로 유지보수 하기 위해서는 기존 작성한 코드가 조금 더 유지보수에 유리하다는 느낌이 있습니다!

어떻게 생각하시는지 궁금합니다!

2023-08-04 16:50 UTC, minju412 commented on src/main/java/com/example/server/domain/member/application/MemberFindService.java
> +	public Member findBySecurityUsername(String username) {
음.. 취향 차이겠지만 저는 Jpa 메서드와 중복이더라도 같은 네이밍이 편할 것 같아요! `memberQueryRepository.findByProviderId()`와 `memberFindService.findByProviderId()` 처럼 사용될 텐데, 완전히 동일한 형태가 아니기 때문에 구분하기 어렵지 않을 것 같습니다.

만약 같은 로직을 `memberFindService. findBySecurityUsername()`으로 나타낸다면, 매번 `MemberFindService`에서 해당 메서드가 어떻게 정의되어 있는지 확인이 필요할 것 같다는 의견입니다! 😅

2023-08-04 17:44 UTC, minju412 commented on src/main/java/com/example/server/domain/pet/api/dto/PetProfileRequest.java
> +	@DateTimeFormat(pattern = "yyyy-MM-dd")
앗 그런 거였군요! 일부는 제가 잘못 이해한 부분도 있었네요!
`LocalDateTime`이 들어올 때 Exception이 발생한다면 더욱 강하게 제약조건을 걸어야 하지 않을까 싶은데 해빈님의 생각은 어떠신지 궁금합니다!

언급해 주신 대로 임보 시작일에 시간까지 들어오지 않을 확률이 크지만, 안전한 게 좋다는 생각이라..ㅎㅎ

2023-08-04 17:58 UTC, minju412 commented on src/main/java/com/example/server/domain/pet/model/Pet.java
>  		validateOwner(owner);
음.. 생성자의 파라미터가 많은 것이 근본적인 원인이겠네요!
[임베디드 타입](https://5bong2-develop.tistory.com/239)을 사용하는 것도 해결책이 될 수 있을 것 같은데, `Pet` 엔티티 안에서 마땅히 공통 속성이랄게 보이지 않네요..🤔

파라미터 수만 줄인다면 기존처럼 분리해서 사용해도 좋을 것 같습니다! (방법은 조금 더 고민해봐요!)

2023-08-04 18:01 UTC, minju412 commented on src/main/java/com/example/server/domain/pet/model/Pet.java
> +		validateType(petReq.getType());
validate 코드가 같은 줄 알았는데 달랐군요..! 교집합만 감싸는 것은.. 유지보수에도 좋지 않지만 보기에도 예쁘지 않네요..ㅎㅎ 저도 기존에 작성한 코드를 유지하는게 좋을 것 같아요!

2023-08-04 18:05 UTC, minju412 commented on src/main/java/com/example/server/domain/pet/model/Pet.java
>  		final String type,
`직접 입력` 필드를 없애고 모든 입력을 가정해 ENUM으로 관리하자는 의견이 맞을까요?! 꼼꼼히 가정할 수만 있다면 그 방법도 괜찮을 것 같네요! 기획팀에 문의해보면 좋을 것 같습니다.

> 강아지 타입이 간혹 홍보메세지나, 다른 용도로 악용될 수 있을 것 같다는 생각도 들더라구요.

이 부분은 제가 확실히 이해를 못해서 미팅 때 직접 여쭤볼게요! :)

2023-08-04 18:07 UTC, minju412 commented on src/main/java/com/example/server/domain/pet/api/dto/PetProfileRequest.java
>  	private Integer age;
저도 소수의 경우 버림한다는 사실은 몰랐는데 우연한 발견이네요..! 🤭 아주 좋습니다! 👍

2023-08-04 18:11 UTC, minju412 commented on src/main/java/com/example/server/domain/pet/model/Pet.java
> +	private LocalDate endTempProtectedDate;
> 임시보호 상태를 어떻게 전역으로 신뢰성 있게 관리할지에 대해서

이 고민이 어떤 고민인지 감이 잘 오지 않아 궁금하네요..!

2023-08-04 18:15 UTC, minju412 commented on src/main/java/com/example/server/domain/pet/model/Pet.java
> +	private LocalDate endTempProtectedDate;
> 다만, 보호 종료로 바뀌었을 때 해당 Pet에 대해 임시보호를 했던 사용자가 어떤 권한이 달라지는지 확인 부탁드립니다.

이 부분 답변드리자면,
- 임시보호 종료 후 PetList 표시 여부는 기획팀에게 문의해 봐야 할 것 같아요!
- 임시보호 종료 유저에게는 `다시보기 컨텐츠`가 제공될 예정입니다.
  - `다시보기 컨텐츠`란 임시보호가 종료된 동물의 일기를 추억별로 제공하는 기능입니다.
  - 임시보호 종료 이후 공허함을 느끼는 사용자의 멘탈 케어를 위한 기능으로, 아이폰  '사진' 앱의 'For You'를 생각하시면 이해에 도움이 될 것 같아요!

2023-08-04 18:22 UTC, minju412 commented on src/main/java/com/example/server/domain/pet/model/Pet.java
> +	private LocalDate endTempProtectedDate;
중도 합류인 만큼 비즈니스 흐름을 따라가기 버겁다는 점 이해가 됩니다 🥲
궁금하거나 힘든 점 있으시면 언제든지 편하게 말씀해 주시고, 지금까지 정해놓은 것보다 앞으로 함께 정할게 훨씬 많으니 화이팅 합시다! 😁

2023-08-08 02:21 UTC, h-beeen reviewed
수정사항
- API Response 폼 변경
```json
{
    "petId": 32,
    "providerId": "2930930513",
    "profileImage": null,
    "petInfo": {
        "name": "아라두루루루",
        "age": 100,
        "type": "DOG",
        "sex": "FEMALE",
        "bio": null
    },
    "petTempProtectedInfo": {
        "status": "IN_PROGRESS",
        "startTempProtectedDate": "2023-08-08",
        "endTempProtectedDate": null
    },
    "isSuccess": true,
    "timestamp": "2023-08-08T11:14:14.714768"
}
```

- Jpa Method에 대한 명명을 변경했습니다.
- 불필요 서비스와 컨트롤러 로직을 제거하고, 펫 생성 API만 설계했습니다.
- 컬럼 제약조건을 추가했습니다.
- Pet Entity에 대한 @Embedded 리팩토링을 실시했습니다.

### 전달사항
- Age에 대한 Integer 제약조건에 대한 고민이 필요합니다. (validate 메소드까지 필요한 일인가?)
- 추가적으로 본 컨트롤러에 대한 테스트 코드는, 다음 PR - RestDocs에서 같이 작성후 PR 예정입니다.
- 서비스, 도메인, 레포지토리에 대한 테스트 코드는 RestDocs 정상작동 확인 이후, 그 다음 PR에서 작성하겠습니다.

2023-08-08 23:46 UTC, h-beeen commented
> Pet Entity에 대한 임베디드 선언 너무 좋았습니다! 고생하셨어요! :D
> 
> `age`에 대해서 `validate` 메소드까지 필요한지에 대해 고민이라고 하셨는데, `age`에 대해서는 유효성 검증이 필요하지 않을 것 같다는 의견이실까요?! 현재 `age` 필드는 1 미만이거나 100 초과일 때 익셉션이 발생하는데, 저는 이 정도의 최소한의 검증은 필요할 것 같다는 의견입니다! 다만 노션을 확인해보니 기획팀에서 정해놓은 제약 조건은 없는 것 같아 논의가 필요할 것 같긴 합니다..!

전달드린 Integer 제약조건은 지난번에 보내주셨던 `정수가 아닐 때 예외` 입니다.
엔티티 자체가 null이거나, String이 들어오는 경우 Parser 오류가 자동으로 던져지는데, 타입캐스팅 되는 객체들에 대해서는 제약하지 못하는 점을, validate으로 처리하려니까 로직이 너무 더러워지더라구요.. 고민중입니다!

2023-08-08 23:46 UTC, merged