Feature/70 - Implement diary creation API
dasi-bom/dasi-bom-server pull request #78
Opened 2023-08-12 13:59 UTC by minju412

### 🧐 Motivation
- 사용자가 일기를 생성할 수 있는 엔드포인트를 추가했습니다.

<br>

### 🎯 Key Changes
- 일기 작성 api 추가
  - 이미지 리스트(`List<MultipartFile>`) 포함해서 요청

<br>

### 💬 To Reviewers
- 리뷰어에게 전달할 말을 작성해 주세요

---

## Member Controller
```JavaScript
POST /diary
Host : localhost:8080
Authorization : Bearer ${ACCESS_TOKEN}
Content-type : `application/json`, `multipartfile/form-data`
```

### `diarySaveRequest`

#### Request Body

```json
{
    "category": "daily",
    "challengeTopic": "tp_1",
    "content": "본문",
    "stamps" : [ 
        "walk", "toy"
    ],
    "isPublic": "True"
}
```

|Name|Type|Description|Constraint
|:----:|:----:|:---:|:--:|
|**category**|String|카테고리<br>(일상인지 챌린지인지)|Not Null<br>`DAILY`, `CHALLENGE` 중 택 1|
|**challengeTopic**|String|챌린지 주제|Nullable<br>`TP_1`, `TP_2`, ..., `TP_N` 중 택 1|
|**content**|String|본문|Nullable<br> 1000자 이내 요청|
|**stamps**|List<String>|스탬프 리스트|Nullable<br>`WALK`, `TREAT`, `TOY`, ...  중 택 1|
|**isPublic**|String|공개 여부|Not Null<br>`True`, `False` 중 택 1|

### `multipartFiles`

2023-08-13 13:38 UTC, h-beeen commented on src/main/java/com/example/server/domain/diary/api/DiaryController.java
> +	@PostMapping(consumes = {MediaType.APPLICATION_JSON_VALUE, MediaType.MULTIPART_FORM_DATA_VALUE})
```suggestion
@PostMapping(consumes = {APPLICATION_JSON_VALUE, MULTIPART_FORM_DATA_VALUE})
```

2023-08-13 13:40 UTC, h-beeen commented on src/main/java/com/example/server/domain/diary/api/DiaryController.java
> +		return ApiResponse.success(null);
ApiResponse가 `200` 상태코드에 `null`을 반환하는 것 같아요!
ResponseBody가 `null` 을 반환하도록 설계하신 이유가 있을까요?

2023-08-13 13:42 UTC, h-beeen commented on src/main/java/com/example/server/domain/diary/application/DiaryService.java
> +	) throws IOException {
이렇게 다수의 파라미터가 들어올 때, 파라미터별로 개행을 주어 자르는 방식을 저도 매우 선호합니다!

다만, 첫 번째 파라미터부터 괄호 밑으로 잘라서 설계한다면, 더욱 파라미터가 직관적으로 인식될 것 같아요.

```suggestion
    public void createDiary(
            String username,
            DiarySaveRequest diarySaveRequest,
            List<MultipartFile> multipartFiles,
            String dirName
    ) throws IOException {
```

2023-08-13 13:46 UTC, h-beeen commented on src/main/java/com/example/server/domain/diary/application/DiaryService.java
> +	) throws IOException {
여기서 `IOException` 을 던지게 설계하도록 의도하신 건지 궁금합니다.

2023-08-13 13:49 UTC, h-beeen commented on src/main/java/com/example/server/domain/diary/application/DiaryService.java
> +		if (!petFindService.findPetsByOwner(member).contains(diarySaveRequest.getPetId())) {
한 문장이 너무 많은 비즈니스 로직을 담고 있는 것 같아요. 행위부터, 검증, 예외까지 3가지 책임을 지고 있는 if문인 것 같아요.

`boolean` 형식으로 해당 행위의 결과만 검증하는 검증 메소드로 분리해도 좋을 것 같아요.

2023-08-13 13:51 UTC, h-beeen commented on src/main/java/com/example/server/domain/diary/application/DiaryService.java
> +		}
```suggestion
diaryStampList = stamps.stream()
    .map(DiaryStamp::of)
    .collect(Collectors.toList());
```

2023-08-13 13:55 UTC, h-beeen commented on src/main/java/com/example/server/domain/diary/application/DiaryService.java
전체적으로 createDiary라는 하나의 메소드가, 너무 많은 행위를 담당하고 있는 것 같아요.
이 부분에 대해서, 관심사에 따라 분리하고, 검증메소드도 필요에 따라 분리하면 더 가독성 높은 코드가 될 것 같아요.

2023-08-13 13:56 UTC, h-beeen commented on src/main/java/com/example/server/domain/diary/application/DiaryService.java
> +		String dirName
String DirName을 파라미터로 설정하신 이유가 궁금합니다.
해당 메소드는 일기 작성외에, 다른 디렉토리에 대한 확장 계획이 있을까요?

2023-08-13 14:01 UTC, h-beeen commented on src/main/java/com/example/server/domain/diary/application/DiaryService.java
> +				? ChallengeTopic.toEnum(diarySaveRequest.getChallengeTopic()) : null,
이렇게 삼항연산자로 나눈 부분들도,
- diarySaveRequest에서 challengerTopic을 가져오는 로직
- 이값이 null인지 검증하는 로직
- null이 아니라면, enum으로 변환하는 로직

이렇게 다양한 책임이 강하게 엮여서 설계된 것 같아요!
이 부분에 대한 분리도 고려하시면 좋을 것 같아요.

2023-08-13 14:02 UTC, h-beeen commented on src/main/java/com/example/server/domain/diary/api/dto/DiarySaveRequest.java
> +	@NotNull(message = "대상 동물은 필수 선택 값입니다.")
`@NotNull` 어노테이션에 메세지를 넣어 SQL 제약조건 상에서 에러 메세지를 표현하는 방법도 되게 좋은 방법인 것 같아요.

저도 Pet 엔티티 수정하면서 같이 이런 방향으로 수정해볼게요.

2023-08-13 14:05 UTC, h-beeen commented on src/main/java/com/example/server/domain/diary/api/dto/DiarySaveRequest.java
> +	private List<String> stamps = new ArrayList<>();
Requset 객체에, `newArrayList<>()`를 할당하신 이유가 궁금합니다.

2023-08-13 14:07 UTC, h-beeen commented on src/main/java/com/example/server/domain/diary/application/DiaryService.java
> +			}
단일 조건문에서 불필요한 if depth가 2번 들어간 것 같아요.
boolean으로 행위에 대한 검증 메소드로 분리하는 방향도 좋을 것 같아요.

2023-08-13 14:11 UTC, h-beeen commented on src/main/java/com/example/server/domain/diary/model/Diary.java
> +		this.images = (images != null) ? images : new ArrayList<>();
이부분도 책임 분리가 필요해보여요!

2023-08-13 14:11 UTC, h-beeen commented on src/main/java/com/example/server/domain/diary/model/Diary.java
> +		this.diaryStamps = (diaryStamps != null) ? diaryStamps : new ArrayList<>();
> 이부분도 책임 분리가 필요해보여요!

2023-08-13 14:16 UTC, h-beeen commented on src/main/java/com/example/server/domain/diary/model/Diary.java
> +	}
여기서 addPet이 어떤 역할과 책임을 가지는지 궁금합니다.

2023-08-13 14:20 UTC, h-beeen commented on src/main/java/com/example/server/domain/diary/model/Diary.java
> +	private Member author;
부모 엔티티인 멤버의 삭제(탈퇴) 발생시, 해당 멤버가 작성한 일기도 삭제할 수 있도록, Cascade 옵션이나 OrphanRemove 옵션을 고려해보는 건 어떻게 생각하세요?

2023-08-13 14:21 UTC, h-beeen commented on src/main/java/com/example/server/domain/diary/model/Diary.java
> +	private List<Image> images = new ArrayList<>();
해당 엔티티를 new ArrayList로 초기화하시는 이유가 있을까요?

2023-08-13 14:22 UTC, h-beeen commented on src/main/java/com/example/server/domain/diary/model/Diary.java
> +	private LocalDateTime deletedDate;
이 객체의 역할은 무엇인가요?

2023-08-13 14:24 UTC, h-beeen commented on src/main/java/com/example/server/domain/diary/model/DiaryStamp.java
> +	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
다른 로직에서는 static Import를 사용해서 축약하셨던 로직으로 기억해요.
이 부분도 깔끔하게 정리하면 좋을 것 같아요.

2023-08-13 14:26 UTC, h-beeen commented on src/main/java/com/example/server/domain/diary/model/Diary.java
비슷한 관심사를 전체적으로 묶어, @Embedded 와 같은 방식으로 조금 더 객체지향적 방식으로 설계하시면 어떨까 싶어요!

2023-08-13 14:28 UTC, h-beeen commented on src/main/java/com/example/server/domain/pet/model/Pet.java
> +	private List<Diary> diaries = new ArrayList<>();
펫과 일기를 양방향 매핑을 하도록 결정하신 이유가 있을까요?

2023-08-13 14:29 UTC, h-beeen commented on src/main/java/com/example/server/domain/stamp/api/StampController.java
> +		return ApiResponse.success(null);
여기도 ResponseBody에 대한 폼이 null로 정해진 이유가 궁금합니다.

2023-08-13 14:32 UTC, minju412 commented on src/main/java/com/example/server/domain/diary/model/Diary.java
> +	private List<Image> images = new ArrayList<>();
`new ArrayList`로 초기화하지 않으면 해당 필드는 기본적으로 null이 들어가게 되고, `add`등을 사용해 해당 필드에 접근할 때 NPE가 발생하기 때문에 미리 초기화 해두었습니다. 예전에 김영한님 강의를 들었을 때 리스트 필드에는 관습적으로 초기화 해두는 것이 좋다고 들은 적도 있었구요..!

2023-08-13 14:33 UTC, h-beeen commented on src/main/java/com/example/server/domain/image/model/Image.java
> +			.build();
부정확한 이미지 URL이 들어왔거나, fileName이 invalid할 경우에 대한 Exception Handling이 가능할까요?

2023-08-13 14:34 UTC, minju412 commented on src/main/java/com/example/server/domain/diary/model/Diary.java
> +	private LocalDateTime deletedDate;
예전에 말씀드렸듯이 저희는 hard delete가 아닌 soft delete 방식을 사용합니다. 해당 일기를 삭제했을 때 db에서 완전히 삭제하지 않고 삭제한 일기임을 나타내는 필드입니다! (`deletedDate` - 삭제한 날짜 / `isDeleted` - 삭제 여부)

2023-08-13 14:36 UTC, h-beeen commented on src/main/java/com/example/server/domain/diary/model/Diary.java
> +	private String content;
SQL 제약조건 외에, 백엔드에서 해당 제약조건 외에, BusinessException으로 리턴하기 위해서, 검증 로직이 필요할 것이라 생각되는데, 어떻게 생각하시는지 궁금합니다.

2023-08-13 14:39 UTC, h-beeen commented on src/main/java/com/example/server/domain/stamp/model/Stamp.java
> +	public static Stamp of(final StampType stampType) {
of 메소드로 stampType 파라미터에 존재하지 않는 stampType이 들어왔을 때, 핸들링 할 수 있는 방법이 있는지 궁금합니다.

2023-08-13 14:39 UTC, h-beeen commented on src/main/java/com/example/server/domain/stamp/model/Stamp.java
> +	}
of 메소드로 stampType 파라미터에 존재하지 않는 stampType이 들어왔을 때, 핸들링 할 수 있는 방법이 있는지 궁금합니다.

2023-08-13 14:42 UTC, h-beeen requested changes
고생 많으셨습니다..!!

컨트롤러/엔티티/서비스가 모두 한 PR에 반영되어서, 리뷰하는데 시간이 꽤 걸렸네요.
많은 시간 코딩하시느라 고생 많으셨어요!

앞으로 이렇게 큰 비즈니스 로직이 오고가는 코드가 작성될 때에는
조금 더 단위로 나눠서 PR 올려주시면 빠른 리뷰에 더 도움이 될 것 같습니다.

수정이 필요하거나 궁금했던 내용들 자세히 코멘트 달아두었습니다.
감사합니다.

2023-08-13 14:45 UTC, minju412 commented on src/main/java/com/example/server/domain/pet/model/Pet.java
> +	private List<Diary> diaries = new ArrayList<>();
아래 보이시는 것처럼 사용자가 특정 동물을 클릭했을 때 각 동물 별로 일기를 확인할 수 있어야 한다는 비즈니스 요구사항 때문입니다!
(옛날 버전이라 레이아웃은 변경될 수 있습니다!)

![스크린샷 2023-08-13 오후 11 42 40](https://github.com/dasi-bom/dasi-bom-server/assets/59405576/653d8830-ff5b-4eea-a96a-bfffc5eaa567)

2023-08-13 14:49 UTC, minju412 commented on src/main/java/com/example/server/domain/diary/model/Diary.java
> +	private String content;
SQL 제약조건으로 검증할 수 없는 디테일한 비즈니스 요구사항이 있다면 검증 로직이 필요하다는 의견에 동의합니다!
하지만 노션에 있는 content 제약조건은 1000자 이내의 영/한/수/특 다 허용되어서 추가 검증 로직이 불필요하다고 판단했는데, 혹시 어떤 제약 조건을 염두에 두는지 궁금합니다.

2023-08-13 15:03 UTC, minju412 commented on src/main/java/com/example/server/domain/diary/application/DiaryService.java
> +	) throws IOException {
MultipartFile을 다루는 과정에서 입출력 문제가 발생할 수 있기 때문에 `IOException`을 던집니다!

2023-08-13 15:19 UTC, minju412 commented on src/main/java/com/example/server/domain/diary/model/Diary.java
> +	}
`addPet`은 pet과 diary의 양방향 관계 설정을 도와주는 utility 메서드입니다. 새로운 일기를 생성할 때, 해당 일기의 대상이 되는 동물을 설정하고, 그 동물이 가지고 있는 일기 리스트에 해당 일기를 추가합니다.

2023-08-13 15:21 UTC, minju412 commented on src/main/java/com/example/server/domain/diary/model/Diary.java
> +	private Member author;
좋은 의견입니다! 하지만 회원 삭제(탈퇴) 시 db에서 회원을 완전히 지우는지, 탈퇴 플래그만 업데이트 하는지 비즈니스 요구사항을 먼저 점검해야할 것 같네요..! 
만약 회원 탈퇴 시 완전 삭제를 한다면 Cascade 옵션을 고려하겠습니다!

2023-08-13 15:25 UTC, minju412 commented on src/main/java/com/example/server/domain/diary/model/Diary.java
네네! 다음 PR에 올리도록 하겠습니다!

2023-08-13 15:47 UTC, minju412 commented on src/main/java/com/example/server/domain/diary/api/DiaryController.java
> +		return ApiResponse.success(null);
앗 임시로 null로 해놓고 수정을 못했네요! 생성된 일기를 응답하도록 코드 변경했습니다!

2023-08-13 15:51 UTC, minju412 commented on src/main/java/com/example/server/domain/diary/application/DiaryService.java
> +		String dirName
생각해보니 굳이 파라미터로 받을 필요가 없을 것 같아 수정했습니다! 생각해보지 못했던 부분인데 감사합니다 :)

2023-08-13 16:10 UTC, minju412 commented on src/main/java/com/example/server/domain/diary/application/DiaryService.java
> +		if (!petFindService.findPetsByOwner(member).contains(diarySaveRequest.getPetId())) {
```java
if (!isPetOwner(member, diarySaveRequest.getPetId())) {
	throw new BusinessException(PET_NOT_FOUND);
}
...
private boolean isPetOwner(Member member, Long petId) {
	return petFindService.findPetsByOwner(member).contains(petId);
}
```
이렇게 분리했는데 의도하신게 맞는지 점검 부탁드립니다!

2023-08-13 16:22 UTC, minju412 commented on src/main/java/com/example/server/domain/diary/application/DiaryService.java
동의합니다! 관심사에 따라 메서드를 나눠봤는데 확인 부탁드립니다!

2023-08-13 16:39 UTC, minju412 commented on src/main/java/com/example/server/domain/diary/application/DiaryService.java
> +				? ChallengeTopic.toEnum(diarySaveRequest.getChallengeTopic()) : null,
수정했습니다! 기능 구현만 생각했던 것 같은데 코드 품질에 대한 리뷰 너무 감사합니다!

2023-08-13 16:44 UTC, minju412 commented on src/main/java/com/example/server/domain/diary/api/dto/DiarySaveRequest.java
> +	private List<String> stamps = new ArrayList<>();
요청 객체에 List 타입을 초기화하지 않으면 클라이언트가 stamps 필드를 요청에서 전달하지 않았을 때 null이 들어가고, NPE가 발생합니다.

2023-08-13 16:47 UTC, minju412 commented on src/main/java/com/example/server/domain/diary/application/DiaryService.java
> +			}
첫 번째 if문은 multiparFiles 이 들어왔는지 검증을 위한 조건문이고, 두 번째 if문은 이미지가 비즈니스 요구사항에서 정의한 값(현재 5개)보다 많이 들어왔을 때 익셉션을 발생시키기 위한 조건문입니다. 해당 로직이 불필요한 if depth라고 생각하신 이유가 궁금합니다!

> boolean으로 행위에 대한 검증 메소드로 분리하는 방향도 좋을 것 같아요.

이 내용은 잘 와닿지 않아 추가 설명 부탁드리고 싶습니다..!

2023-08-13 17:03 UTC, minju412 commented on src/main/java/com/example/server/domain/diary/model/DiaryStamp.java
> +	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
취향차이겠지만 저는 이러한 경우에는 static import 를 사용하지 않아도 된다고 생각합니다!
저는 주로 상수를 모아놓은 유틸리티 클래스(ex. 에러코드)를 만들어서 사용하는 경우에만 static import를 사용하는 편입니다.

static import 를 많이 사용하면 다른 사람이 읽었을 때 어떤 클래스에 정의된 메서드나 상수를 사용하는지 알 수 없기 때문에 가독성이 저하될 수도 있다고 생각하는데 해빈님의 생각도 궁금합니다!

2023-08-13 17:10 UTC, minju412 commented on src/main/java/com/example/server/domain/stamp/api/StampController.java
> +		return ApiResponse.success(null);
이 부분도 생성된 스탬프를 응답하도록 수정했습니다!

2023-08-13 17:21 UTC, minju412 commented on src/main/java/com/example/server/domain/image/model/Image.java
> +			.build();
부정확한 URL이 들어왔을 때 예외처리를 하려면 정상적인 URL인지 검증을 해야하는데 그 방법을 잘 모르겠네요..🤔 
검증 방법에 대한 아이디어 있으시다면 전달 부탁드립니다!

fileName에 대한 검증은, 지금 생각나는건 확장자를 제한할 수는 있을 것 같네요! 해당 예외처리는 추가했습니다. 
마찬가지로 다른 의견 있으시면 말씀해 주세요!

2023-08-13 17:25 UTC, minju412 commented
큰 볼륨의 PR을 전달드리게 되어서 죄송합니다 🥲 리뷰 고생 많으셨고 감사합니다!
이후부터는 더 작은 단위로 나눠서 올릴 수 있도록 하겠습니다!

구현하면서도 조금 복잡한가..? 싶은 부분이 있었는데 콕 집어주셨네요 👍
메서드를 분리를 통해 책임을 감소하는데에 신경써서 리팩토링 해봤습니다.

꼼꼼한 리뷰 감사드립니다!

2023-08-14 16:00 UTC, h-beeen commented on src/main/java/com/example/server/domain/diary/api/DiaryController.java
> +			diary.getIsPublic()
컨트롤러가 비즈니스 로직을 갖고 있다고 생각하는데 어떻게 생각하시나요!!?

2023-08-14 16:04 UTC, h-beeen commented on src/main/java/com/example/server/domain/diary/model/Diary.java
> +	private String content;
1000자의 검증 로직을 BusinessException으로 던지는 로직을 권유드려봅니다.
예컨데, 배포 환경에서 의도치 않은 사이드이펙트로  DB의 제약 조건이 변경된다고 하더라도
코드레벨에서 해당 사안을 검증하는 로직이 필요하다고 판단했습니다.

2023-08-14 16:06 UTC, h-beeen commented on src/main/java/com/example/server/domain/diary/model/Diary.java
> +	private LocalDateTime deletedDate;
삭제한 게시글을 다시 살릴 기능을 제공할 예정이 아니고, 단순히 서버에 백업할 용도라고 한다면,
삭제 일기 테이블로 백업하여 관리하는 건 어떨까요? 그 부분이 쿼리 성능 면에서는 훨씬 나을 것 같다는 생각이 듭니다!

2023-08-14 16:50 UTC, minju412 commented on src/main/java/com/example/server/domain/diary/model/Diary.java
> +	private String content;
현재 `DiarySaveRequest`에 1000자 제한 조건을 걸어놓았기 때문에 1000자를 초과한 요청이 들어온다면 컨트롤러 단에서 익셉션을 발생시킵니다. 같은 검증 로직을 Diary에도 추가하는 것을 권유하시는 걸까요?

2023-08-16 08:24 UTC, minju412 commented on src/main/java/com/example/server/domain/diary/api/DiaryController.java
> +			diary.getIsPublic()
동의합니다! 이를 해결하기 위해서 두 가지를 고민했습니다. 
- 응답 dto 클래스 내부에 변환 로직을 적용
- 응답 객체로 조립하기 위한 assembler 생성

첫 번째 방식은 dto 클래스가 변환 로직과 데이터를 함께 담고 있기 때문에 단일 책임 원칙에 위배된다고 생각했습니다.
따라서 두 번째 방식을 선택했습니다. 
결과적으로 코드가 더욱 모듈화 되어 단일 책임 원칙을 지키고, dto 클래스는 순수한 데이터를 담는 역할을 수행합니다.

2023-08-17 02:00 UTC, h-beeen commented on src/main/java/com/example/server/domain/diary/model/DiaryStamp.java
> +	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
저같은 경우는 어노테이션에 적용되는 타입과 enum타입은 명시적으로 가독이 가능하다고 생각해서, enum 사용을 즐기는 편이에요!
다만, 어떻게 사용하던 상관은 없지만, 프로젝트 전체적으로 방향성이 통일되면 좋을 것 같아요. (사용/미사용/특정 경우에 사용)

2023-08-17 02:04 UTC, h-beeen commented on src/main/java/com/example/server/domain/diary/application/DiaryService.java
> +		if (!petFindService.findPetsByOwner(member).contains(diarySaveRequest.getPetId())) {
포스트컨디션으로 객체 책임에 맞게 잘 분리되고, 예외까지 검증이 잘 되는 코드인 것 같아요!

2023-08-17 02:06 UTC, h-beeen commented on src/main/java/com/example/server/domain/diary/application/DiaryService.java
> +			}
```java
if(multipartFiles == null || multipartFiles.size() > IMAGE_LIST_SIZE){
     throw new BusinessException(---);
}

2023-08-17 02:10 UTC, h-beeen commented on src/main/java/com/example/server/domain/diary/model/Diary.java
> +	private String content;
만약 1000자에서 1200자로 비즈니스 요구사항이 변한다고 했을 때
해당 컨트롤러에 얽혀있는 모든 Dto 클래스의 제약조건을 수정하는 방법과
해당 비즈니스 로직을 담당하는 서비스의 제약조건을 수정하는 방법 중
어떤 것이 유연한 설계인가? 라는 질문을 드리고 싶습니다!

또한, 우리는 BusinessExcetpion이라는 전역 예외처리를 적용중인데,
서비스 로직에서 우리가 예상 가능한 익셉션에 대해서, 
2차 검증이 필수적으로 진행되어야 한다고 생각합니다.

2023-08-17 02:16 UTC, h-beeen approved these changes
고생 많으셨습니다!

훨씬 객체지향적이고, 책임이 분리된 느낌으로 변경된 것 같습니다!
소소하게 코드 레벨에서 조금씩 수정해야 할 부분이 있지만,
빠른 개발 진행을 위해 Approve 드리겠습니다!

추후 머지 이후, 조금 더 수정이 필요한 부분에 대해 추후 같이 얘기 나눠봐요!
감사합니다.

2023-08-17 08:23 UTC, merged